# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param synth.incrementalSynthesisCache C:/Users/marco/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-15080-DESKTOP-1M6FA7L/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/hlocal/Practica3/Practica3.cache/wt [current_project]
set_property parent.project_path C:/hlocal/Practica3/Practica3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo c:/hlocal/Practica3/Practica3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/hlocal/Practica3/Practica3.srcs/sources_1/imports/Downloads/sumador.vhd
  C:/hlocal/Practica3/Practica3.srcs/sources_1/new/mult8b.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/hlocal/Practica3/Practica3.srcs/constrs_1/imports/Downloads/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/hlocal/Practica3/Practica3.srcs/constrs_1/imports/Downloads/Basys3_Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top mult8b -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mult8b.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mult8b_utilization_synth.rpt -pb mult8b_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
