# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/hlocal/ExamenPasado4/ficheros/Basys3_Master.xdc

# IP: ip/mem32x512/mem32x512.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mem32x512 || ORIG_REF_NAME==mem32x512} -quiet] -quiet
